version: 2.1

defaults: &defaults
  working_directory: ~/qb-animation-library
  docker:
    - image: circleci/node:latest-browsers

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package.json checksum
            # when this file is changed, this key will fail
            - qb-animation-library-{{ checksum "package-lock.json" }}-{{ checksum ".circleci/config.yml" }}
            - qb-animation-library-{{ checksum "package-lock.json" }}
            # Find the most recent cache used from any branch
            - qb-animation-library-
      - run:
          name: Install Dependencies
          command: npm i
      - save_cache:
          key: qb-animation-library-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum ".circleci/config.yml" }}
          paths:
            - node_modules

      - persist_to_workspace:
          root: .
          paths:
            - .

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/qb-animation-library
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - .

  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/qb-animation-library
      - run: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Release
          command: yarn run release

workflows:
  version: 2
  build_and_test:
    jobs:
      - install

      - build:
          requires:
            - install
          filters:
            tags:
              only: /.*/

      - release:
          requires:
            - build
          filters:
            branches:
              only:
                - master
